intel-retail/retail-use-cases

- use-cases/ovms_server/start_ovms_server.sh
> feat: Adding server run script

- .gitignore
- Makefile
- README.md
- use-cases/gst_capi/Makefile
- use-cases/gst_capi/add_camera-simulator.yml
- use-cases/gst_capi/add_replicas_capi_face_detection.yml
- use-cases/gst_capi/add_replicas_capi_yolov5.yml
- use-cases/gst_capi/add_replicas_capi_yolov5_ensemble.yml
- use-cases/gst_capi/pipelines/capi_yolov5/main.cpp
- use-cases/gst_capi/pipelines/capi_yolov5_ensemble/main.cpp
- use-cases/gst_capi/pipelines/face_detection/main.cpp
- use-cases/gst_capi/run_gst_capi.sh
close: #**[506](https://github.com/intel-retail/automated-self-checkout/issues/506)**
- ## gst_capi use cases:
There are three different pipelines for gst_capi use cases: capi_yolov5, capi_yolov5_ensemble, and capi_face_detection.
- to build all capis run:
```bash
make build-all-capis
```
- to build one at a time run:
- for capi_yolov5
```bash
make build-capi_yolov5
```
- for capi_yolov5_ensemble
```bash
make build-capi_yolov5_ensemble
```
- for capi_face_detection
```bash
make build-capi_face_detection
```
- run one capi_yolov5 pipeline
```bash
make run-capi_yolov5
```
- shutdown capi_yolov5
```bash
make down-capi_yolov5
```
- run one capi_yolov5_ensemble pipeline
```bash
make run-capi_yolov5_ensemble
```
- shutdown capi_yolov5_ensemble
```bash
make …
```
> feat: add replica docker compose for gst-capi use cases

- Makefile
- README.md
- use-cases/grpc_go/Dockerfile
- use-cases/grpc_go/Makefile
- use-cases/grpc_go/docker-compose_grpc_go.yml
- use-cases/grpc_go/entrypoint.sh
- use-cases/grpc_go/main.go
close: #**[521](https://github.com/intel-retail/automated-self-checkout/issues/521)**
- ## grpc_go use case:
- to build run:
```bash
make build-grpc-go
```
- run one grpc_go pipeline
```bash
make run-grpc-go
```
- run two grpc_go pipelines
```bash
PIPELINE_COUNT=2 make run-grpc-go
```
- shutdown Docker containers
```bash
make down-grpc-go
```
- clean up the output results
```bash
make clean-results
```
> feat: add grpc-go retail-use case replica docker-compose

- use-cases/dlstreamer/requirements.txt
> fix: Dependabot updates

- .gitignore
- Makefile
- smoke-tests/Makefile
- smoke-tests/requirements.txt
- smoke-tests/use-cases_smoke_tests.py
close: #**17**
- to run smoke tests: `make run-smoke-tests` from the project root directory
- should see all PASSED for all test cases
> feat: add smoke tests for running use-cases pipelines

- use-cases/gst_capi/Dockerfile
FIXES: #20
close: **#20**
- follow the details on issue #20 on how to reproduce the defects, now it should fix this defect
-
> fix: resolve the CAPI build issue on dependency changes intel-onevpl

- .gitignore
- Makefile
- models-downloader/Dockerfile.bitModel
- models-downloader/downloadOVMSModels.sh
- use-cases/gst_capi/Dockerfile
- use-cases/gst_capi/Dockerfile.yolov8
- use-cases/gst_capi/Makefile
- use-cases/gst_capi/add_gst_capi_face_detection.yml
- use-cases/gst_capi/add_gst_capi_yolov5.yml
- use-cases/gst_capi/add_gst_capi_yolov5_ensemble.yml
- use-cases/gst_capi/add_gst_capi_yolov8_ensemble.yml
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/Makefile
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/buffersqueue.cpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/buffersqueue.hpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_interface.h
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_library_internal_manager.cpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/custom_node_library_internal_manager.hpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/efficientnetb0_node.cpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/efficientnetb0_node_debug.cpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/main.cpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/opencv_utils.hpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/queue.hpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/utils.hpp
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/yolo_efficientnet.sh
- use-cases/gst_capi/res/capi_yolov8_ensemble.env
- use-cases/gst_capi/res/yolov8/config-yolov8.json
- build capi-yolov8 ensemble docker image: 
```console
make build-capi_yolov8_ensemble
```
- make clean-results
- to run:  make run-capi_yolov8_ensemble
- to run two pipelines:   `PIPELINE_COUNT=2 make run-capi_yolov8_ensemble`
- to shutdown:  `make down-capi_yolov8_ensemble`
> Add capi yolov8 docker compose use cases for gst-capi

- CONTRIBUTING.md
- LICENSE
> doc: Update license file and contributing guide

- Makefile
> Adding render command

- swarm/README.md
- swarm/docker-compose.yml
> Adding swarm support

- use-cases/dlstreamer/Dockerfile
- Updating dlstreamer use-case to use v2024.1.1-dev-ubuntu22
- Go to `./use-cases/dlstreamer`
- Run `make build` to build the image
- Run `make run` to run
- See results in the upper level results directory
> feat: update dlstreamer use-case to v2024.1.1

- .github/workflows/scorecard.yml
- README.md
> fix: Update scorecard version and add tags

- use-cases/demos/object_detection/pytorch-yolo/entrypoint.sh
- use-cases/demos/object_detection/pytorch-yolo/yolov5_object_detection.py
View cumulative average fps in pipeline logs under results folder
> fix: add fps in pipeline logs

- use-cases/gst_capi/Dockerfile.yolov8
- use-cases/gst_capi/helm/Dockerfile_yolov8
- use-cases/gst_capi/helm/Makefile
- use-cases/gst_capi/pipelines/capi_yolov8_ensemble/Makefile
- Fixes mqtt lib build issue found with capi_yolov8 image build
> fix: update base capi Makefiles and Dockerfiles to include mqtt libs

- README.md
> doc: update readme with Intel optimization packages for pytorch ultralytics based object detection pipeline

- use-cases/demos/.gitignore
- use-cases/demos/add_demo_pytorch_object_detection.yml
- use-cases/demos/object_detection/pytorch-yolo/entrypoint.sh
- use-cases/demos/object_detection/pytorch-yolo/yolov5_ultralytics_object_detection.py
- use-cases/demos/pytorch-yolov5-env.txt
- use-cases/demos/requirements-pytorch.txt
Added intel optimized pipelines for pytorch based yolov5 object detection
1) Modify USE_ULTRALYTICS and/or INTEL_OPTIMIZED variables (0 or 1) in pytorch-yolov5-env.txt to select the required implementation.
2) make build_pytorch
3) make run_pytorch_object_detection
4) Check pipeline logs for fps.
On my i5, non-ultralytics pipeline ran faster (5.4 fps) compared to when using ultralytics with (3.88 fps) or without (3.55 fps) intel optimization for yolov5. Accuracy wise ultralytics is performing better.
Note: I modified the entrypoint.sh to control which pipeline gets run based on USE_ULTRALYTICS and INTEL_OPTIMIZED set in pytorch-yolov5-env.txt. I didn't wanted to create more yaml files and make commands for these different implementations. We can do this later if …
> feat: intel optimized pipelines for pytorch object detection

- README.md
- use-cases/demos/add_demo_tensorflow_keras_classification.yml
- use-cases/demos/classification/tensorflow-keras/entrypoint.sh
- use-cases/demos/classification/tensorflow-keras/liteRT_keras_classification.py
- use-cases/demos/tensorflow-keras-env.txt
- In root level directory, run `make update-submodules download-sample-media`
- Do `cd use-cases/demos` to navigate to correct dir
- Change the `USE_TFLITE=0` to 1 to use Tensorflow Lite interpreter within the `use-cases/demos/tensorflow-keras-env.txt` file
- Run `make run_tensorflow_keras_classification`
- You should see an inference window pop-up on screen with a coca-cola video and either the title `TensorflowLite-Keras Classification` or `Tensorflow-Keras Classification` depending on whether you selected to use TFLite or TF
> Document and Implement Tensorflow Lite interpreter

- .github/release.yml
create config for release notes 
> feat: Add configuration file for release notes

- use-cases/continual_learning/app.py
- use-cases/continual_learning/camera-demo.py
- use-cases/continual_learning/model/__init__.py
- use-cases/continual_learning/model/losses.py
- use-cases/continual_learning/model/slda.py
- use-cases/continual_learning/model/utils.py
- use-cases/continual_learning/notebook/slda_frozen_classification_cl.ipynb
Continual learning demo missing models directory due to gitignore rules. Updated the directory to avoid conflict.
> fix: update models directory due to gitignore rules

- .github/.reviewdogConfig.yml
- .github/workflows/reviewdog.yaml
We are changing pep8 to pycodestyle , this fixes the reviewdog github action works properly.
close: #**63**
> fix: Change pep8 to pycodestyle for fixing failure due to reviewdog GitHub action

- use-cases/continual_learning/README.md
- use-cases/continual_learning/images/Green_Grape/Images.txt
- use-cases/continual_learning/images/Red_Apple/Images.txt
- use-cases/continual_learning/requirements.txt
> fix: revert back tensorflow & other package versions

- use-cases/continual_learning/requirements.txt
> fix: update python packages

- use-cases/continual_learning/app.py
- use-cases/continual_learning/model/slda.py
-In SLDA.py: Replaced Keras-managed training (super().fit()) with a custom fit() that manually processes NumPy samples one-by-one, adds input validation, and ensures graph compatibility using tf.cond in call().
-In app.py: Applied manual tensor-to-NumPy conversion approach rather than using direct TensorFlow dataset training approach.
> Manually handling NumPy inputs.
